//      *********    DO NOT MODIFY THIS FILE     *********
//      This file is regenerated by a design tool. Making
//      changes to this file can cause errors.
namespace Expression.Blend.SampleData.DesignDataSource
{
	using System; 

// To significantly reduce the sample data footprint in your production application, you can set
// the DISABLE_SAMPLE_DATA conditional compilation constant and disable sample data at runtime.
#if DISABLE_SAMPLE_DATA
	internal class DesignDataSource { }
#else

	public class DesignDataSource : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		public DesignDataSource()
		{
			try
			{
				System.Uri resourceUri = new System.Uri("/VitalStats;component/SampleData/DesignDataSource/DesignDataSource.xaml", System.UriKind.Relative);
				if (System.Windows.Application.GetResourceStream(resourceUri) != null)
				{
					System.Windows.Application.LoadComponent(this, resourceUri);
				}
			}
			catch (System.Exception)
			{
			}
		}

		private Profiles _Profiles = new Profiles();

		public Profiles Profiles
		{
			get
			{
				return this._Profiles;
			}
		}
	}

	public class ProfilesItem : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		private string _Name = string.Empty;

		public string Name
		{
			get
			{
				return this._Name;
			}

			set
			{
				if (this._Name != value)
				{
					this._Name = value;
					this.OnPropertyChanged("Name");
				}
			}
		}

		private bool _IsProtected = false;

		public bool IsProtected
		{
			get
			{
				return this._IsProtected;
			}

			set
			{
				if (this._IsProtected != value)
				{
					this._IsProtected = value;
					this.OnPropertyChanged("IsProtected");
				}
			}
		}
	}

	public class Profiles : System.Collections.ObjectModel.ObservableCollection<ProfilesItem>
	{ 
	}
#endif
}
