using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Pocketailor.Model
{
    // Use the StaticFile Python script to generate this
    public partial class Static
    {


        public static Dictionary<RegionId, RegionId> RegionParents = new Dictionary<RegionId, RegionId>()
        {
{ RegionId.Worldwide, RegionId.Worldwide },
{ RegionId.Europe, RegionId.Worldwide },
{ RegionId.NorthAmerica, RegionId.Worldwide },
{ RegionId.Australasia, RegionId.Worldwide },
{ RegionId.Asia, RegionId.Worldwide },
{ RegionId.SouthAmerica, RegionId.Worldwide },
{ RegionId.Africa, RegionId.Worldwide },
{ RegionId.Ireland, RegionId.UK },
{ RegionId.UK, RegionId.Europe },
{ RegionId.France, RegionId.Europe },
{ RegionId.Italy, RegionId.Europe },
{ RegionId.Germany, RegionId.Europe },
{ RegionId.Denmark, RegionId.Europe },
{ RegionId.Sweden, RegionId.Europe },
{ RegionId.Norway, RegionId.Europe },
{ RegionId.Finland, RegionId.Europe },
{ RegionId.Spain, RegionId.Europe },
{ RegionId.Austria, RegionId.Europe },
{ RegionId.Switzerland, RegionId.Europe },
{ RegionId.Netherlands, RegionId.Europe },
{ RegionId.Belgium, RegionId.Europe },
{ RegionId.Portugal, RegionId.Europe },
{ RegionId.Russia, RegionId.Europe },
{ RegionId.Iceland, RegionId.Europe },
{ RegionId.Poland, RegionId.Europe },
{ RegionId.Latvia, RegionId.Europe },
{ RegionId.Slovakia, RegionId.Europe },
{ RegionId.CzechRepublic, RegionId.Europe },
{ RegionId.Croatia, RegionId.Europe },
{ RegionId.Slovenia, RegionId.Europe },
{ RegionId.Greece, RegionId.Europe },
{ RegionId.Turkey, RegionId.Europe },
{ RegionId.Bulgaria, RegionId.Europe },
{ RegionId.Romania, RegionId.Europe },
{ RegionId.Hungary, RegionId.Europe },
{ RegionId.Lithuania, RegionId.Europe },
{ RegionId.Liechtenstein, RegionId.Europe },
{ RegionId.Luxembourg, RegionId.Europe },
{ RegionId.Albania, RegionId.Europe },
{ RegionId.Balarus, RegionId.Europe },
{ RegionId.Estonia, RegionId.Europe },
{ RegionId.FaroeIslands, RegionId.Europe },
{ RegionId.Serbia, RegionId.Europe },
{ RegionId.Ukraine, RegionId.Europe },
{ RegionId.US, RegionId.NorthAmerica },
{ RegionId.Canada, RegionId.NorthAmerica },
{ RegionId.Mexico, RegionId.SouthAmerica },
{ RegionId.Brazil, RegionId.SouthAmerica },
{ RegionId.Belize, RegionId.SouthAmerica },
{ RegionId.Jamaica, RegionId.SouthAmerica },
{ RegionId.Argentina, RegionId.SouthAmerica },
{ RegionId.Bolivia, RegionId.SouthAmerica },
{ RegionId.Chile, RegionId.SouthAmerica },
{ RegionId.Colombia, RegionId.SouthAmerica },
{ RegionId.CostaRica, RegionId.SouthAmerica },
{ RegionId.DominicanRepublic, RegionId.SouthAmerica },
{ RegionId.Ecuador, RegionId.SouthAmerica },
{ RegionId.ElSalvador, RegionId.SouthAmerica },
{ RegionId.Guatemala, RegionId.SouthAmerica },
{ RegionId.Honduras, RegionId.SouthAmerica },
{ RegionId.Nicaragua, RegionId.SouthAmerica },
{ RegionId.Panama, RegionId.SouthAmerica },
{ RegionId.Praguay, RegionId.SouthAmerica },
{ RegionId.Peru, RegionId.SouthAmerica },
{ RegionId.PuertoRico, RegionId.SouthAmerica },
{ RegionId.Uraguay, RegionId.SouthAmerica },
{ RegionId.Venezuela, RegionId.SouthAmerica },
{ RegionId.Zimbabwe, RegionId.Africa },
{ RegionId.SouthAfrica, RegionId.Africa },
{ RegionId.Egypt, RegionId.Africa },
{ RegionId.Tunisia, RegionId.Africa },
{ RegionId.Morocco, RegionId.Africa },
{ RegionId.Algeria, RegionId.Africa },
{ RegionId.Libya, RegionId.Africa },
{ RegionId.Kenya, RegionId.Africa },
{ RegionId.Japan, RegionId.Asia },
{ RegionId.China, RegionId.Asia },
{ RegionId.Korea, RegionId.Asia },
{ RegionId.HongKong, RegionId.Asia },
{ RegionId.Bahrain, RegionId.Asia },
{ RegionId.Iraq, RegionId.Asia },
{ RegionId.Jordan, RegionId.Asia },
{ RegionId.Kuwait, RegionId.Asia },
{ RegionId.Lebanon, RegionId.Asia },
{ RegionId.Oman, RegionId.Asia },
{ RegionId.Qatar, RegionId.Asia },
{ RegionId.SaudiArabia, RegionId.Asia },
{ RegionId.Syria, RegionId.Asia },
{ RegionId.UnitedArabEmirates, RegionId.Asia },
{ RegionId.Yemen, RegionId.Asia },
{ RegionId.Armenia, RegionId.Asia },
{ RegionId.Azerbaijan, RegionId.Asia },
{ RegionId.Macau, RegionId.Asia },
{ RegionId.Singapore, RegionId.Asia },
{ RegionId.Taiwan, RegionId.Asia },
{ RegionId.Maldives, RegionId.Asia },
{ RegionId.Philippines, RegionId.Asia },
{ RegionId.TrinidadTobago, RegionId.Asia },
{ RegionId.Iran, RegionId.Asia },
{ RegionId.Georgia, RegionId.Asia },
{ RegionId.India, RegionId.Asia },
{ RegionId.Isreal, RegionId.Asia },
{ RegionId.Kazakhstan, RegionId.Asia },
{ RegionId.Brunei, RegionId.Asia },
{ RegionId.Malaysia, RegionId.Asia },
{ RegionId.Mongolia, RegionId.Asia },
{ RegionId.Thailand, RegionId.Asia },
{ RegionId.Pakistan, RegionId.Asia },
{ RegionId.Uzbekistan, RegionId.Asia },
{ RegionId.Vietnam, RegionId.Asia },
{ RegionId.SriLanka, RegionId.Asia },
{ RegionId.Bangladesh, RegionId.Asia },
{ RegionId.Australia, RegionId.Australasia },
{ RegionId.NewZealand, RegionId.Australasia },

            

        };
    }


}
