using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Pocketailor.Model
{

//    // Use the StaticFile Python script to generate this
//    public enum RegionId
//    {
//        Global = 1,
//        Europe = 2,
//        NorthAmerica = 3,
//        Australasia = 4,
//        Asia = 5,
//        SouthAmerica = 6,
//        Africa = 7,
//        Ireland = 8,
//        UK = 9,
//        France = 10,
//        Italy = 11,
//        Germany = 12,
//        Denmark = 13,
//        Sweden = 14,
//        Norway = 15,
//        Finland = 16,
//        Spain = 17,
//        Austria = 18,
//        Switzerland = 19,
//        Netherlands = 20,
//        Belgium = 21,
//        Portugal = 22,
//        Russia = 23,
//        Iceland = 25,
//        Poland = 26,
//        Latvia = 27,
//        Slovakia = 28,
//        CzechRepublic = 29,
//        Croatia = 30,
//        Slovenia = 31,
//        Greece = 32,
//        Turkey = 33,
//        Bulgaria = 34,
//        Romania = 35,
//        Hungary = 36,
//        Lithuania = 37,
//        Liechtenstein = 38,
//        Luxembourg = 39,
//        Albania = 40,
//        Balarus = 41,
//        Estonia = 42,
//        FaroeIslands = 43,
//        Serbia = 44,
//        Ukraine = 45,
//        US = 46,
//        Canada = 47,
//        Mexico = 48,
//        Brazil = 49,
//        Belize = 50,
//        Jamaica = 51,
//        Argentina = 52,
//        Bolivia = 53,
//        Chile = 54,
//        Colombia = 55,
//        CostaRica = 56,
//        DominicanRepublic = 57,
//        Ecuador = 58,
//        ElSalvador = 59,
//        Guatemala = 60,
//        Honduras = 61,
//        Nicaragua = 62,
//        Panama = 63,
//        Praguay = 64,
//        Peru = 65,
//        PuertoRico = 66,
//        Uraguay = 67,
//        Venezuela = 68,
//        Zimbabwe = 69,
//        SouthAfrica = 70,
//        Egypt = 71,
//        Tunisia = 72,
//        Morocco = 73,
//        Algeria = 74,
//        Libya = 75,
//        Kenya = 76,
//        Japan = 77,
//        China = 78,
//        Korea = 79,
//        HongKong = 80,
//        Bahrain = 81,
//        Iraq = 82,
//        Jordan = 83,
//        Kuwait = 84,
//        Lebanon = 85,
//        Oman = 86,
//        Qatar = 87,
//        SaudiArabia = 88,
//        Syria = 89,
//        UnitedArabEmirates = 90,
//        Yemen = 91,
//        Armenia = 92,
//        Azerbaijan = 93,
//        Macau = 94,
//        Singapore = 95,
//        Taiwan = 96,
//        Maldives = 97,
//        Philippines = 98,
//        TrinidadTobago = 99,
//        Iran = 100,
//        Georgia = 101,
//        India = 102,
//        Isreal = 103,
//        Kazakhstan = 104,
//        Brunei = 105,
//        Malaysia = 106,
//        Mongolia = 107,
//        Thailand = 108,
//        Pakistan = 109,
//        Uzbekistan = 110,
//        Vietnam = 111,
//        SriLanka = 112,
//        Bangladesh = 113,
//        Australia = 114,
//        NewZealand = 115,

//    }



//    public static partial class Lookup {

//        // Use the StaticFile Python script to generate this
//        public static Dictionary<RegionId, string> Regions = new Dictionary<RegionId,string>() 
//        {
//{ RegionId.Global, "Global" },
//{ RegionId.Europe, "Europe" },
//{ RegionId.NorthAmerica, "North America" },
//{ RegionId.Australasia, "Australasia" },
//{ RegionId.Asia, "Asia" },
//{ RegionId.SouthAmerica, "South America" },
//{ RegionId.Africa, "Africa" },
//{ RegionId.Ireland, "Ireland" },
//{ RegionId.UK, "UK" },
//{ RegionId.France, "France" },
//{ RegionId.Italy, "Italy" },
//{ RegionId.Germany, "Germany" },
//{ RegionId.Denmark, "Denmark" },
//{ RegionId.Sweden, "Sweden" },
//{ RegionId.Norway, "Norway" },
//{ RegionId.Finland, "Finland" },
//{ RegionId.Spain, "Spain" },
//{ RegionId.Austria, "Austria" },
//{ RegionId.Switzerland, "Switzerland" },
//{ RegionId.Netherlands, "Netherlands" },
//{ RegionId.Belgium, "Belgium" },
//{ RegionId.Portugal, "Portugal" },
//{ RegionId.Russia, "Russia" },
//{ RegionId.Isreal, "Isreal" },
//{ RegionId.Iceland, "Iceland" },
//{ RegionId.Poland, "Poland" },
//{ RegionId.Latvia, "Latvia" },
//{ RegionId.Slovakia, "Slovakia" },
//{ RegionId.CzechRepublic, "Czech Republic" },
//{ RegionId.Croatia, "Croatia" },
//{ RegionId.Slovenia, "Slovenia" },
//{ RegionId.Greece, "Greece" },
//{ RegionId.Turkey, "Turkey" },
//{ RegionId.Bulgaria, "Bulgaria" },
//{ RegionId.Romania, "Romania" },
//{ RegionId.Hungary, "Hungary" },
//{ RegionId.Lithuania, "Lithuania" },
//{ RegionId.Liechtenstein, "Liechtenstein" },
//{ RegionId.Luxembourg, "Luxembourg" },
//{ RegionId.Albania, "Albania" },
//{ RegionId.Balarus, "Belarus" },
//{ RegionId.Estonia, "Estonia" },
//{ RegionId.FaroeIslands, "Islands" },
//{ RegionId.Serbia, "Serbia" },
//{ RegionId.Ukraine, "Ukraine" },
//{ RegionId.US, "United States" },
//{ RegionId.Canada, "Canada" },
//{ RegionId.Mexico, "Mexico" },
//{ RegionId.Brazil, "Brazil" },
//{ RegionId.Belize, "Belize" },
//{ RegionId.Jamaica, "Jamaica" },
//{ RegionId.Argentina, "Argentina" },
//{ RegionId.Bolivia, "Bolivia" },
//{ RegionId.Chile, "Chile" },
//{ RegionId.Colombia, "Colombia" },
//{ RegionId.CostaRica, "Rica" },
//{ RegionId.DominicanRepublic, "Republic" },
//{ RegionId.Ecuador, "Ecuador" },
//{ RegionId.ElSalvador, "Salvador" },
//{ RegionId.Guatemala, "Guatemala" },
//{ RegionId.Honduras, "Honduras" },
//{ RegionId.Nicaragua, "Nicaragua" },
//{ RegionId.Panama, "Panama" },
//{ RegionId.Praguay, "Paraguay" },
//{ RegionId.Peru, "Peru" },
//{ RegionId.PuertoRico, "Rico" },
//{ RegionId.Uraguay, "Uraguay" },
//{ RegionId.Venezuela, "Venezuela" },
//{ RegionId.Zimbabwe, "Zimbabwe" },
//{ RegionId.SouthAfrica, "South Africa" },
//{ RegionId.Egypt, "Egypt" },
//{ RegionId.Tunisia, "Tunisia" },
//{ RegionId.Morocco, "Morocco" },
//{ RegionId.Algeria, "Algeria" },
//{ RegionId.Libya, "Libya" },
//{ RegionId.Kenya, "Kenya" },
//{ RegionId.Japan, "Japan" },
//{ RegionId.China, "China" },
//{ RegionId.Korea, "Korea" },
//{ RegionId.HongKong, "Hong Kong" },
//{ RegionId.Bahrain, "Bahrain" },
//{ RegionId.Iraq, "Iraq" },
//{ RegionId.Jordan, "Jordan" },
//{ RegionId.Kuwait, "Kuwait" },
//{ RegionId.Lebanon, "Lebanon" },
//{ RegionId.Oman, "Oman" },
//{ RegionId.Qatar, "Qatar" },
//{ RegionId.SaudiArabia, "Arabia" },
//{ RegionId.Syria, "Syria" },
//{ RegionId.UnitedArabEmirates, "Arab Emirates" },
//{ RegionId.Yemen, "Yemen" },
//{ RegionId.Armenia, "Armenia" },
//{ RegionId.Azerbaijan, "Azerbaijan" },
//{ RegionId.Macau, "Macau" },
//{ RegionId.Singapore, "Singapore" },
//{ RegionId.Taiwan, "Taiwan" },
//{ RegionId.Maldives, "Maldives" },
//{ RegionId.Philippines, "Philippines" },
//{ RegionId.TrinidadTobago, "Trinidad and Tobago" },
//{ RegionId.Iran, "Iran" },
//{ RegionId.Georgia, "Georgia" },
//{ RegionId.India, "India" },
//{ RegionId.Kazakhstan, "Kazakhstan" },
//{ RegionId.Brunei, "Brunei" },
//{ RegionId.Malaysia, "Malaysia" },
//{ RegionId.Mongolia, "Mongolia" },
//{ RegionId.Thailand, "Thailand" },
//{ RegionId.Pakistan, "Pakistan" },
//{ RegionId.Uzbekistan, "Uzbekistan" },
//{ RegionId.Vietnam, "Vietnam" },
//{ RegionId.SriLanka, "Sri Lanka" },
//{ RegionId.Bangladesh, "Bangladesh" },
//{ RegionId.Australia, "Australia" },
//{ RegionId.NewZealand, "New Zealand" },
//        };

//    }


}
